# Instructions:
# The title of the entries (e.g., openai, anthropic, etc. below) should match the `credentials` field in `models.yaml`.
# For specific providers, check the [LiteLLM](https://docs.litellm.ai/docs/providers) documentation for the required parameters.

openai:
  api_key: API_KEY

anthropic:
  api_key: API_KEY

gemini:
  api_key: API_KEY

deepseek:
  api_key: API_KEY

xai:
  api_key: API_KEY

azure:
  api_key: API_KEY
  api_base: API_BASE
  api_version: API_VERSION

bedrock:
  aws_access_key_id: ACCESS_KEY_ID
  aws_secret_access_key: SECRET_ACCESS_KEY
  aws_region_name: REGION_NAME
